### ISSUE TITLE
sparsity

### ISSUE THREAD

**Issue by ghost** [HolmesShuan/Dynamic-Network-Surgery-Caffe-Reimplementation#1]
thanks for your work, do you have good result about convolution with sparsity 90%? or in your best result, what sparsity do your set?

**Comment by HolmesShuan** [comment]
To be honest, I haven't tried 90% sparse convolution layer. According to my knowledge, that kind of sparsity could only exist in fully connected layers or a few convolution layers without a huge loss in accuracy. I have tried 50% ConV on resnet. About 2% higher than baseline @Top-5 on ImageNet.

**Comment by ghost** [comment]
I have same result with you, did you have other nice result about pruning with other papers? I tried this work and deep compression and ssl,but I find these sparsity methods cost a lot time and without a good acc and sparsity

**Comment by HolmesShuan** [comment]
DNS seems the fastest algorithm,so far. You want a light network or just to prune the pre-trained dense network?

**Comment by ghost** [comment]
I foucs on model compression, I think light work is more important for Embedded system such as phone, but a good network is time-consuming to find, I think pruning + low bit is a good choice,do you have other advices for model compression, especially for fast inference? or will a chat with wechat?

**Comment by HolmesShuan** [comment]
U may interest in [BMXNET](https://arxiv.org/abs/1705.09864) , [SqueezeNet](https://arxiv.org/abs/1602.07360) and [PerfBLAS](https://github.com/PerfXLab). There are other high-performance Binary GEMM libs, u may turn to GitHub Search for more help.
